#!/bin/bash

# Installation script for testframework

source settings.sh

echo
echo "Install the test framework!"
echo "${TESTFRAMEWORK_INSTALL_SCRIPT}"
echo "into directory 'scripts'"
echo "All content of the directory 'scripts' will be removed!"
echo

if [[ $1 != '--no-prompt' ]]; then
	while read -p "Continue (y) or exit(e): y/e "; do
		if [[ $REPLY == "y" || $REPLY == "Y" ]]; then
			break
		elif [[ $REPLY == "e" || $REPLY == "E" ]]; then
			exit 2
		fi
	done
fi

rm -rfv scripts
rm -rfv testframeInstaller_*

wget "${TESTFRAMEWORK_SOURCE}"
gunzip -v "${TESTFRAMEWORK_INSTALL_DOWNLOAD}"
chmod -v +x "${TESTFRAMEWORK_INSTALL_SCRIPT}"
"./${TESTFRAMEWORK_INSTALL_SCRIPT}" "$(realpath scripts)"

echo "DONE"
exit 0
