#!/bin/bash

# run all tests

if ! [[ -x scripts/bin/runbtf ]]; then
	echo -e "\033[31mNo test framework installed!\nUse the script 'installtestframework' to install the test framework in subdirectory 'scripts'.\033[0m" >&2
	exit 2
fi
scripts/bin/runbtf --directory tests --no-prompt
